# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-19 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191019_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
