# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-19 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20191019_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=models.CharField(choices=[('LinuxL', 'Linux中高级'), ('PythonFullStack', 'Python高级全栈开发')], max_length=128, verbose_name='咨询课程'),
        ),
    ]
